// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC16V-RkpWl-yeTcSOl3bpmcrMV6Lu56Y',
    appId: '1:860647598710:web:1abf52b6766eb82b4acd57',
    messagingSenderId: '860647598710',
    projectId: 'inomarket-app',
    authDomain: 'inomarket-app.firebaseapp.com',
    storageBucket: 'inomarket-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCnMwXyPYX1COqKIQxISItodkhYzzaE3A',
    appId: '1:860647598710:android:413851e122f6ef3c4acd57',
    messagingSenderId: '860647598710',
    projectId: 'inomarket-app',
    storageBucket: 'inomarket-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADdtwJ27mrNSxnNQ3Ct1VaQNyTNKkB-9E',
    appId: '1:860647598710:ios:1eb58d36d0b1d3044acd57',
    messagingSenderId: '860647598710',
    projectId: 'inomarket-app',
    storageBucket: 'inomarket-app.firebasestorage.app',
    iosBundleId: 'com.example.inomarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADdtwJ27mrNSxnNQ3Ct1VaQNyTNKkB-9E',
    appId: '1:860647598710:ios:1eb58d36d0b1d3044acd57',
    messagingSenderId: '860647598710',
    projectId: 'inomarket-app',
    storageBucket: 'inomarket-app.firebasestorage.app',
    iosBundleId: 'com.example.inomarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC16V-RkpWl-yeTcSOl3bpmcrMV6Lu56Y',
    appId: '1:860647598710:web:b9774a9032c5776b4acd57',
    messagingSenderId: '860647598710',
    projectId: 'inomarket-app',
    authDomain: 'inomarket-app.firebaseapp.com',
    storageBucket: 'inomarket-app.firebasestorage.app',
  );
}
